on:
  pull_request_target:
    branches: [master, main]
    types: [closed]

permissions: {}
#  actions: read|write|none
#  checks: read|write|none
#  contents: read|write|none
#  deployments: read|write|none
#  id-token: read|write|none
#  issues: read|write|none
#  discussions: read|write|none
#  packages: read|write|none
#  pages: read|write|none
#  pull-requests: read|write|none
#  repository-projects: read|write|none
#  security-events: read|write|none
#  statuses: read|write|none
  
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: "debug"
        run: echo $JSON 
        env:
          JSON: ${{ toJSON(github.event) }}
     
  comment_rollback:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == 'true'
    steps: 
      # TODO: reach out somewhere and get an actual version.
      - name: "Fetch current version"
        run: echo "" >> $GITHUB_OUTPUT
        
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
